services:
  snake-game:
    build: .
    container_name: snake-game
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      - DETAILED_LOGS=true
    command: [ "./webserver", "--detailed-logs" ]
